#+OPTIONS: toc:nil
#+BEGIN_HTML
---
layout: post
title: 「EXWM」でEmacsをウインドウマネージャとして使う
---
#+END_HTML

* はじめに

  EXWM (https://github.com/ch11ng/exwm) はタイトルのとおり，Emacsをタイル型ウインドウマネージャにするものです。[[https://github.com/Wilfred/remacs][Remacs]]でも動きます。どのような見た目になるかは公式のスクリーンショットがわかりやすいです (https://github.com/ch11ng/exwm/wiki/Screenshots)。

  EXWMの導入方法や基本的な使い方はこちらを参考にしました (https://medium.com/@h.taiju/emacs-as-window-manager-68ddcec3ba97)。

* 手順
** パッケージのインストール

   MELPAに登録されています。

   #+BEGIN_SRC 
   M-x p-ins exwm
   #+END_SRC

** xinitrcのコピー

   パッケージのインストールが終わると，elpa/exwmの中にxinitrcがあるので，それをホームフォルダにコピーして名前を.xinitrcに変更します。既に.xinitrcを作っている方は事前に必ずバックアップをしておいてください。なおremacsを使っている方はexwmのxinitrc最終行のemacsをremacsに書き換えておきます。

** init.elへの追加

   #+BEGIN_SRC 
   (require 'exwm)
   (require 'exwm-config)
   (exwm-config-default)
   #+END_SRC

** ログインメニューへの登録

   /usr/share/xsessionsにemacs.desktopというファイルを作成し，以下の内容で保存してください (remacsを使っている場合はExecの部分がremacsになります)。保存し終えたら再起動します。

   #+BEGIN_SRC 
   [Desktop Entry]
   Name=EXWM
   Comment=Emacs-based window manager
   Exec=emacs
   Type=Application
   #+END_SRC

   ログイン画面の右上か右下にデスクトップ環境を選択するアイコンがあると思うので，EXWMを選んでログインしてください (参考: https://www.youtube.com/watch?v=Gk9-q8tXbMs)。

** 基本的な使い方

   - ソフトウェアを起動する: S-& (SuperキーはWinキーに割り当てられていることが多い)
   - ワークスペースを行き来する: S-w

   ワークスペースを増やす，マルチディスプレイの方法など，詳細な設定は公式のwikiを見てください。

   日本語入力の方法については別記事を作りました (→ [[https://jamcha-aa.github.io/2018/03/12/exwm-jp.html][EXWMで日本語を入力する]])
